# Generated by Django 5.2.4 on 2025-07-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_details_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_working_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
